SET IDENTITY_INSERT [dbo].[Usuarios] ON
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (1, N'Ariana.1', N'Ariana.1', N'arianagrande@gmail.com', N'Grande', N'Ariana', 2)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (2, N'Taylor.1', N'Taylor.1', N'taylorswift@gmail.com', N'Swift', N'Taylor', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (3, N'Lanita!1', N'Lanita!1', N'lanadelrey@gmail.com', N'Del Rey', N'Lana', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (4, N'XCXWorld1!', N'XCXWorld1!', N'charlixcx@gmail.com', N'XCX', N'Charli', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (5, N'underWater!1', N'underWater!1', N'chuu@gmail.com', N'Kim', N'JiWoo', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (6, N'Gowonnie!2', N'Gowonnie!2', N'gowon@gmail.com', N'Park', N'Chaewon', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (7, N'Twice2!', N'Twice2!', N'nayeon@gmail.com', N'Im', N'Nayeon', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (8, N'Momo.1', N'Momo.1!', N'momo@gmail.com', N'Hirai', N'Momo', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (9, N'Hyeju.1', N'Hyeju.1', N'hyeju@gmail.com', N'Son', N'Hyeju', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (10, N'Hyunjin.1', N'Hyunjin.1', N'hyunjin@gmail.com', N'Kim', N'Hyunjin', 1)
INSERT INTO [dbo].[Usuarios] ([Id], [Contrasenia_Password], [ContraseniaEncriptada_ValorContrasenia], [Email_DireccionEmail], [NombreCompleto_Apellido], [NombreCompleto_Nombre], [Rol_RolValor]) VALUES (11, N'Eltorero123.', N'Eltorero123.', N'chayanne@gmail.com', N'Torero', N'Chayanne', 2)
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
